package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type Vec3 struct {
	X, Y, Z float64
}

type Triangle struct {
	A, B, C int
}

type Model struct {
	Vertices []Vec3
	Faces    []Triangle
}

func ParseOBJ(path string) (*Model, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("cannot open file: %w", err)
	}
	defer f.Close()

	model := &Model{}
	scanner := bufio.NewScanner(f)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		switch fields[0] {
		case "v":
			if len(fields) < 4 {
				return nil, fmt.Errorf("line %d: invalid vertex (need x y z)", lineNum)
			}
			x, ex := strconv.ParseFloat(fields[1], 64)
			y, ey := strconv.ParseFloat(fields[2], 64)
			z, ez := strconv.ParseFloat(fields[3], 64)
			if ex != nil || ey != nil || ez != nil {
				return nil, fmt.Errorf("line %d: invalid float in vertex", lineNum)
			}
			model.Vertices = append(model.Vertices, Vec3{x, y, z})
		case "f":
			if len(fields) < 4 {
				return nil, fmt.Errorf("line %d: face must have at least 3 indices", lineNum)
			}
			indices := make([]int, 0, len(fields)-1)
			for _, tok := range fields[1:] {
				parts := strings.SplitN(tok, "/", 2)
				idx, err := strconv.Atoi(parts[0])
				if err != nil {
					return nil, fmt.Errorf("line %d: invalid face index '%s'", lineNum, tok)
				}
				if idx < 0 {
					idx = len(model.Vertices) + idx + 1
				}
				if idx <= 0 || idx > len(model.Vertices) {
					return nil, fmt.Errorf("line %d: face index %d out of range", lineNum, idx)
				}
				indices = append(indices, idx-1)
			}
			for i := 1; i < len(indices)-1; i++ {
				model.Faces = append(model.Faces, Triangle{indices[0], indices[i], indices[i+1]})
			}
		default:
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading file: %w", err)
	}
	if len(model.Vertices) == 0 {
		return nil, fmt.Errorf("no vertices found in OBJ file")
	}
	if len(model.Faces) == 0 {
		return nil, fmt.Errorf("no faces found in OBJ file")
	}
	return model, nil
}

func WriteOBJ(path string, vertices []Vec3, faces [][4]int) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("cannot create output file: %w", err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	fmt.Fprintln(w, "# Voxelized OBJ - generated by voxelizer")
	for _, v := range vertices {
		fmt.Fprintf(w, "v %f %f %f\n", v.X, v.Y, v.Z)
	}
	for _, face := range faces {
		fmt.Fprintf(w, "f %d %d %d %d\n", face[0]+1, face[1]+1, face[2]+1, face[3]+1)
	}
	return w.Flush()
}

func DeriveOutputPath(inputPath string) string {
	dir := filepath.Dir(inputPath)
	base := filepath.Base(inputPath)
	ext := filepath.Ext(base)
	name := strings.TrimSuffix(base, ext)
	return filepath.Join(dir, name+"-voxelized.obj")
}
